import { ON_DESKTOP_DEVICE, ON_FAVORITES_PAGE, ON_POST_LIST_PAGE } from "@/lib/environment";
import { Preferences } from "@/app/context/preferences";

export const FAVORITES_SEARCH_GALLERY_ENABLED = ON_FAVORITES_PAGE || (ON_POST_LIST_PAGE && Preferences.postList.enabled.value);
export const FAVORITES_SEARCH_GALLERY_DISABLED = !FAVORITES_SEARCH_GALLERY_ENABLED;

export const PERFORMANCE_PROFILE = Preferences.app.performanceProfile.value;

export const GALLERY_ENABLED = (ON_FAVORITES_PAGE || ON_POST_LIST_PAGE) && (PERFORMANCE_PROFILE === "normal" || PERFORMANCE_PROFILE === "medium");
export const GALLERY_DISABLED = !GALLERY_ENABLED;

export const TOOLTIP_ENABLED = (ON_FAVORITES_PAGE || ON_POST_LIST_PAGE) && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== "potato";
export const TOOLTIP_DISABLED = !TOOLTIP_ENABLED;

export const TAG_EDITOR_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE;
export const TAG_EDITOR_DISABLED = !TAG_EDITOR_ENABLED;

export const CAPTIONS_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== "potato";
export const CAPTIONS_DISABLED = !CAPTIONS_ENABLED;

export const POST_OVERLAY_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== "potato";
export const POST_OVERLAY_DISABLED = !POST_OVERLAY_ENABLED;

export const DOWNLOADER_ENABLED = ON_FAVORITES_PAGE;
export const DOWNLOADER_DISABLED = !DOWNLOADER_ENABLED;
