import { ON_DESKTOP_DEVICE, ON_FAVORITES_PAGE, ON_SEARCH_PAGE } from "../../lib/environment";
import { PerformanceProfile } from "../../types/ui";
import { Preferences } from "./preferences";

export const FAVORITES_SEARCH_GALLERY_ENABLED = ON_FAVORITES_PAGE || (ON_SEARCH_PAGE && Preferences.searchPagesEnabled.value);
export const FAVORITES_SEARCH_GALLERY_DISABLED = !FAVORITES_SEARCH_GALLERY_ENABLED;

export const PERFORMANCE_PROFILE = Preferences.performanceProfile.value;

export const GALLERY_ENABLED = (ON_FAVORITES_PAGE || ON_SEARCH_PAGE) && (PERFORMANCE_PROFILE === PerformanceProfile.Normal || PERFORMANCE_PROFILE === PerformanceProfile.Medium);
export const GALLERY_DISABLED = !GALLERY_ENABLED;

export const TOOLTIP_ENABLED = (ON_FAVORITES_PAGE || ON_SEARCH_PAGE) && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== PerformanceProfile.Potato;
export const TOOLTIP_DISABLED = !TOOLTIP_ENABLED;

export const TAG_MODIFIER_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE;
export const TAG_MODIFIER_DISABLED = !TAG_MODIFIER_ENABLED;

export const CAPTIONS_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== PerformanceProfile.Potato;
export const CAPTIONS_DISABLED = !CAPTIONS_ENABLED;

export const SAVED_SEARCHES_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE;
export const SAVED_SEARCHES_DISABLED = !SAVED_SEARCHES_ENABLED;

export const AUTOCOMPLETE_ENABLED = ON_FAVORITES_PAGE;
export const AUTOCOMPLETE_DISABLED = !AUTOCOMPLETE_ENABLED;

export const DOWNLOADER_ENABLED = ON_FAVORITES_PAGE;
export const DOWNLOADER_DISABLED = !DOWNLOADER_ENABLED;

export const SEARCH_PAGE_ENABLED = ON_SEARCH_PAGE && Preferences.searchPagesEnabled.value;
export const SEARCH_PAGE_DISABLED = !SEARCH_PAGE_ENABLED;
