import { FavoriteIndicatorStyle, GalleryFavoriteStyle, Layout, PerformanceProfile } from "@/types/ui";
import { ON_DESKTOP_DEVICE, ON_MOBILE_DEVICE } from "@/lib/environment";
import { Rating, SortingMethod } from "@/types/search";
import { OverlayMode } from "@/features/post_overlay/types/overlay_mode";
import { Preference } from "@/lib/storage/preference";

export const Preferences = {
  addButtonsVisible: new Preference("showAddFavoriteButtons", false),
  allowedRatings: new Preference<Rating>("allowedRatings", 7),
  autoplayActive: new Preference("autoplayActive", false),
  autoplayForward: new Preference("autoplayForward", true),
  autoplayImageDuration: new Preference("autoplayImageDuration", 3_000),
  autoplayMinimumVideoDuration: new Preference("autoplayMinimumVideoDuration", 5_000),
  autoplayPaused: new Preference("autoplayPaused", false),
  backgroundOpacity: new Preference("backgroundOpacity", "1"),
  captionsVisible: new Preference("showCaptions", false),
  colorScheme: new Preference("colorScheme", "black"),
  columnCount: new Preference("columnCount", ON_MOBILE_DEVICE ? 3 : 6),
  desktopSearchBoxHeight: new Preference("desktopSearchBoxHeight", 50),
  downloadBatchSize: new Preference("downloadBatchSize", 250),
  downloadButtonsVisible: new Preference("showDownloadButtons", false),
  excludeBlacklist: new Preference("excludeBlacklist", false),
  favoriteFinderId: new Preference("findFavorite", ""),
  favoritesLayout: new Preference<Layout>("layout", "tiler--column"),
  galleryMenuDockedLeft: new Preference("dockGalleryMenuLeft", ON_DESKTOP_DEVICE),
  galleryMenuEnabled: new Preference("galleryMenuEnabled", ON_MOBILE_DEVICE),
  galleryMenuPinned: new Preference("galleryMenuPinned", ON_MOBILE_DEVICE),
  headerEnabled: new Preference("showHeader", true),
  hintsEnabled: new Preference("showHints", false),
  infiniteScroll: new Preference("infiniteScroll", false),
  maximizeToggleFavoriteButtons: new Preference("maximizeToggleFavoriteButtons", false),
  mobileGalleryEnabled: new Preference("mobileGalleryEnabled", true),
  optionsVisible: new Preference("showOptions", false),
  performanceProfile: new Preference<PerformanceProfile>("performanceProfile", PerformanceProfile.Normal),
  postOverlayEnabled: new Preference("postOverlayEnabled", false),
  overlayMode: new Preference<OverlayMode>("overlayMode", "tag"),
  removeButtonsVisible: new Preference("showRemoveFavoriteButtons", false),
  resultsPerPage: new Preference("resultsPerPage", 150),
  rowHeight: new Preference("rowSize", 7),
  savedSearchesVisible: new Preference("savedSearchVisibility", false),
  savedSearchSuggestions: new Preference("savedSearchSuggestions", false),
  savedSearchTutorial: new Preference("savedSearchTutorial", false),
  searchPageAddButtonsVisible: new Preference("showSearchPageAddFavoriteButtons", false),
  searchPageColumnCount: new Preference("searchPageColumnCount", ON_MOBILE_DEVICE ? 3 : 6),
  searchPageFavoriteIndicator: new Preference("searchPageFavoriteIndicator", false),
  searchPageFavoriteIndicatorStyle: new Preference<FavoriteIndicatorStyle>("searchPageFavoriteIndicatorStyle", "border"),
  searchPageGalleryFavoriteStyle: new Preference<GalleryFavoriteStyle>("searchPageGalleryFavoriteStyle", "border"),
  searchPageInfiniteScroll: new Preference("searchPageInfiniteScroll", false),
  searchPageLayout: new Preference<Layout>("searchPageLayout", "tiler--column"),
  searchPageRowHeight: new Preference("searchPageRowSize", 7),
  searchPageUpscaleThumbs: new Preference("upscaleSearchPageThumbs", ON_DESKTOP_DEVICE),
  searchPageEnabled: new Preference("enableOnSearchPages", false),
  showOnHover: new Preference("showOnHover", false),
  sortAscending: new Preference("sortAscending", false),
  sortingMethod: new Preference<SortingMethod>("sortingMethod", "default"),
  tagAliasing: new Preference("tagAliasing", false),
  tooltipEnabled: new Preference("showTooltip", false),
  searchPageTooltipEnabled: new Preference("searchPageShowTooltip", false),
  uiVisible: new Preference("showUi", true),
  videoMuted: new Preference("videoMuted", false),
  videoVolume: new Preference("videoVolume", 1)
};
