import { Layout, PerformanceProfile, Rating, SortingMethod } from "../../../types/common_types";
import { ON_DESKTOP_DEVICE, ON_MOBILE_DEVICE } from "../flags/intrinsic_flags";
import { Preference } from "./preference";

export const Preferences = {
  savedSearchesVisible: new Preference("savedSearchVisibility", false),
  savedSearchSuggestionsEnabled: new Preference("savedSearchSuggestions", false),
  savedSearchTutorialEnabled: new Preference("savedSearchTutorial", false),
  captionsVisible: new Preference("showCaptions", false),
  tooltipsVisible: new Preference("showTooltip", false),
  showOnHoverEnabled: new Preference("showOnHover", false),
  tagAliasingEnabled: new Preference("tagAliasing", false),
  allowedRatings: new Preference<Rating>("allowedRatings", 7),
  favoriteFinderId: new Preference("findFavorite", ""),
  searchPagesEnabled: new Preference("enableOnSearchPages", false),
  performanceProfile: new Preference<PerformanceProfile>("performanceProfile", PerformanceProfile.NORMAL),
  favoritesLayout: new Preference<Layout>("layout", "column"),
  searchPageLayout: new Preference<Layout>("searchPageLayout", "column"),
  excludeBlacklistEnabled: new Preference("excludeBlacklist", false),
  resultsPerPage: new Preference("resultsPerPage", 200),
  sortAscendingEnabled: new Preference("sortAscending", false),
  sortingMethod: new Preference<SortingMethod>("sortingMethod", "default"),
  optionsVisible: new Preference("showOptions", false),
  columnCount: new Preference("columnCount", ON_MOBILE_DEVICE ? 3 : 6),
  rowSize: new Preference("rowSize", 7),
  dockGalleryMenuLeft: new Preference("dockGalleryMenuLeft", ON_DESKTOP_DEVICE),
  uiVisible: new Preference("showUI", true),
  infiniteScrollEnabled: new Preference("infiniteScroll", false),
  galleryMenuPinned: new Preference("galleryMenuPinned", ON_MOBILE_DEVICE),
  galleryMenuEnabled: new Preference("galleryMenuEnabled", ON_MOBILE_DEVICE),
  removeButtonsVisible: new Preference("showRemoveFavoriteButtons", false),
  addButtonsVisible: new Preference("showAddFavoriteButtons", false),
  hintsEnabled: new Preference("showHints", false),
  headerEnabled: new Preference("showHeader", true),
  colorScheme: new Preference("colorScheme", "black"),
  backgroundOpacity: new Preference("backgroundOpacity", "1"),
  videoVolume: new Preference("videoVolume", 1),
  videoMuted: new Preference("videoMuted", false),
  autoplayActive: new Preference("autoplayActive", false),
  autoplayPaused: new Preference("autoplayPaused", false),
  autoplayImageDuration: new Preference("autoplayImageDuration", 3000),
  autoplayMinimumVideoDuration: new Preference("autoplayMinimumVideoDuration", 5000),
  autoplayForward: new Preference("autoplayForward", true),
  downloadBatchSize: new Preference("downloadBatchSize", 250),
  downloadButtonsVisible: new Preference("showDownloadButtons", false),
  mobileGalleryEnabled: new Preference("mobileGalleryEnabled", true),
  upscaleThumbsOnSearchPage: new Preference("upscaleSearchPageThumbs", false),
  searchPageInfiniteScrollEnabled: new Preference("searchPageInfiniteScroll", false)
};
