import { ON_DESKTOP_DEVICE, ON_FAVORITES_PAGE, ON_SEARCH_PAGE } from "./environment";
import { PerformanceProfile } from "../../types/ui";
import { Preferences } from "../preferences/preferences";

export const PERFORMANCE_PROFILE = Preferences.performanceProfile.value;

export const FAVORITES_SEARCH_GALLERY_ENABLED = ON_FAVORITES_PAGE || (ON_SEARCH_PAGE && Preferences.searchPages.value);
export const FAVORITES_SEARCH_GALLERY_DISABLED = !FAVORITES_SEARCH_GALLERY_ENABLED;

export const GALLERY_ENABLED = (ON_FAVORITES_PAGE || ON_SEARCH_PAGE) && (PERFORMANCE_PROFILE === PerformanceProfile.NORMAL || PERFORMANCE_PROFILE === PerformanceProfile.MEDIUM);
export const GALLERY_DISABLED = !GALLERY_ENABLED;

export const TOOLTIP_ENABLED = (ON_FAVORITES_PAGE || ON_SEARCH_PAGE) && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== PerformanceProfile.POTATO;
export const TOOLTIP_DISABLED = !TOOLTIP_ENABLED;

export const TAG_MODIFIER_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE;
export const TAG_MODIFIER_DISABLED = !TAG_MODIFIER_ENABLED;

export const CAPTIONS_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE && PERFORMANCE_PROFILE !== PerformanceProfile.POTATO;
export const CAPTIONS_DISABLED = !CAPTIONS_ENABLED;

export const SAVED_SEARCHES_ENABLED = ON_FAVORITES_PAGE && ON_DESKTOP_DEVICE;
export const SAVED_SEARCHES_DISABLED = !SAVED_SEARCHES_ENABLED;

export const AUTOCOMPLETE_ENABLED = ON_FAVORITES_PAGE;
export const AUTOCOMPLETE_DISABLED = !AUTOCOMPLETE_ENABLED;

export const DOWNLOADER_ENABLED = ON_FAVORITES_PAGE;
export const DOWNLOADER_DISABLED = !DOWNLOADER_ENABLED;
