export const FavoritesId = {
  root: "favorites-root",
  toolbar: "favorites-toolbar",
  workspace: "favorites-workspace",
  drawerTrack: "favorites-drawer-track",
  contentPane: "favorites-content-pane",
  toolbarGrid: "favorites-toolbar-grid",
  aboutSlot: "favorites-about-slot",
  aboutVersion: "favorites-about-version",
  aboutHelp: "favorites-about-help",
  searchBox: "favorites-search-box",
  status: "favorites-search-status",
  resultsCount: "results-count-label",
  loadStatus: "favorites-load-status-label",
  loadProgressBar: "favorites-load-progress-bar",
  searchField: "favorites-search-field",
  searchFieldInner: "favorites-search-field-inner",
  searchButton: "favorites-search-button",
  drawerToggleSlot: "favorites-drawer-toggle-slot",
  drawerToggleButton: "favorites-drawer-toggle-button",
  searchActions: "favorites-search-actions",
  clearButton: "clear-button",
  pagination: "favorites-pagination",
  rangeIndicator: "pagination-range-label",
  gotoPagePopover: "goto-page-popover",
  gotoPageInput: "goto-page-input",
  buttonsSlot: "favorites-button-slot",
  drawer: "favorites-drawer",
  drawerSidebar: "favorites-drawer-sidebar",
  drawerViews: "favorites-drawer-views"
} as const;

export const FavoritesClass = {
  drawerSidebarIcon: "favorites-drawer-sidebar-icon",
  drawerSidebarIconLabel: "favorites-drawer-sidebar-icon-label",
  drawerView: "favorites-drawer-view",
  drawerTitle: "favorites-drawer-title",
  drawerTitleLabel: "favorites-drawer-title-label",
  drawerTitleAction: "favorites-drawer-title-action",
  drawerPanel: "favorites-drawer-panel",
  drawerSection: "favorites-drawer-section",
  drawerSectionTitle: "favorites-drawer-section-title",
  drawerHelpLinks: "favorites-drawer-help-links",
  drawerHelpLink: "favorites-drawer-help-link"
} as const;
