import { FavoriteLayout, Rating, SortingMethod } from "../../types/primitives/primitives";
import { PerformanceProfile } from "../../types/primitives/enums";
import { Preference } from "./preference";

export const Preferences = {
  savedSearchesEnabled: new Preference("savedSearchSuggestions", false),
  savedSearchesVisible: new Preference("savedSearchVisibility", false),
  savedSearchSuggestionsEnabled: new Preference("savedSearchSuggestions", false),
  savedSearchTutorialEnabled: new Preference("savedSearchTutorial", false),
  captionsVisible: new Preference("showCaptions", false),
  tooltipsVisible: new Preference("showTooltip", false),
  showOnHoverEnabled: new Preference("showOnHover", false),
  tagAliasingEnabled: new Preference("tagAliasing", false),
  allowedRatings: new Preference<Rating>("allowedRatings", 7),
  favoriteFinderId: new Preference("findFavorite", ""),
  searchPagesEnabled: new Preference("enableOnSearchPages", false),
  performanceProfile: new Preference<PerformanceProfile>("performanceProfile", PerformanceProfile.HIGH),
  favoritesLayout: new Preference<FavoriteLayout>("layout", "column"),
  excludeBlacklistEnabled: new Preference("excludeBlacklist", false),
  resultsPerPage: new Preference("resultsPerPage", 200),
  sortAscendingEnabled: new Preference("sortAscending", false),
  sortingMethod: new Preference<SortingMethod>("sortingMethod", "default"),
  optionsVisible: new Preference("showOptions", false),
  columnCount: new Preference("columnCount", 6),
  rowSize: new Preference("rowSize", 7),
  dockGalleryMenuLeft: new Preference("dockGalleryMenuLeft", true),
  uiVisible: new Preference("showUI", true),
  infiniteScrollEnabled: new Preference("infiniteScroll", false),
  galleryMenuPinned: new Preference("galleryMenuPinned", true),
  galleryMenuEnabled: new Preference("galleryMenuEnabled", false),
  removeButtonsVisible: new Preference("showRemoveFavoriteButtons", false),
  addButtonsVisible: new Preference("showAddFavoriteButtons", false),
  fancyThumbHoveringEnabled: new Preference("fancyThumbHovering", true),
  hintsEnabled: new Preference("showHints", false),
  headerEnabled: new Preference("showHeader", true),
  colorScheme: new Preference("colorScheme", "black"),
  backgroundOpacity: new Preference("backgroundOpacity", "1"),
  videoVolume: new Preference("videoVolume", 1),
  videoMuted: new Preference("videoMuted", false),
  autoplayActive: new Preference("autoplayActive", false),
  autoplayPaused: new Preference("autoplayPaused", false),
  autoplayImageDuration: new Preference("autoplayImageDuration", 3000),
  autoplayMinimumVideoDuration: new Preference("autoplayMinimumVideoDuration", 5000),
  autoplayForward: new Preference("autoplayForward", true),
  downloadBatchSize: new Preference("downloadBatchSize", 250),
  downloadButtonsVisible: new Preference("showDownloadButtons", false)
};
