import {FavoriteLayout, Rating, SortingMethod} from "../../types/primitives/primitives";
import {PerformanceProfile} from "../../types/primitives/enums";
import {Preference} from "./preference";

export const Preferences = {
  savedSearchSuggestions: new Preference("savedSearchSuggestions", false),
  showSavedSearches: new Preference("savedSearchVisibility", false),
  savedSearchTutorial: new Preference("savedSearchTutorial", false),
  showCaptions: new Preference("showCaptions", false),
  showTooltip: new Preference("showTooltip", false),
  showOnHover: new Preference("showOnHover", false),
  tagAliasing: new Preference("tagAliasing", false),
  allowedRatings: new Preference<Rating>("allowedRatings", 7),
  favoriteFinder: new Preference("findFavorite", ""),
  enableOnSearchPages: new Preference("enableOnSearchPages", false),
  performanceProfile: new Preference<PerformanceProfile>("performanceProfile", PerformanceProfile.HIGH),
  layout: new Preference<FavoriteLayout>("layout", "column"),
  excludeBlacklist: new Preference("excludeBlacklist", false),
  resultsPerPage: new Preference("resultsPerPage", 200),
  sortAscending: new Preference("sortAscending", false),
  sortingMethod: new Preference<SortingMethod>("sortingMethod", "default"),
  showOptions: new Preference("showOptions", false),
  columnCount: new Preference("columnCount", 6),
  rowSize: new Preference("rowSize", 7),
  dockGalleryMenuLeft: new Preference("dockGalleryMenuLeft", true),
  showUI: new Preference("showUI", true),
  infiniteScroll: new Preference("infiniteScroll", false),
  galleryMenuPinned: new Preference("galleryMenuPinned", true),
  galleryMenuEnabled: new Preference("galleryMenuEnabled", false),
  showRemoveFavoriteButtons: new Preference("showRemoveFavoriteButtons", false),
  showAddFavoriteButtons: new Preference("showAddFavoriteButtons", false),
  fancyThumbHovering: new Preference("fancyThumbHovering", true),
  showHints: new Preference("showHints", false),
  showHeader: new Preference("showHeader", true),
  colorScheme: new Preference("colorScheme", "black"),
  backgroundOpacity: new Preference("backgroundOpacity", "1"),
  videoVolume: new Preference("videoVolume", 1),
  videoMuted: new Preference("videoMuted", false),
  autoplayActive: new Preference("autoplayActive", false),
  autoplayPaused: new Preference("autoplayPaused", false),
  autoplayImageDuration: new Preference("autoplayImageDuration", 3000),
  autoplayMinimumVideoDuration: new Preference("autoplayMinimumVideoDuration", 5000),
  autoplayForward: new Preference("autoplayForward", true),
  downloadBatchSize: new Preference("downloadBatchSize", 250),
  showDownloadButtons: new Preference("showDownloadButtons", false)
};
